name: almuhafiz_teachers
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # UI & Design Packages
  cupertino_icons: ^1.0.8                    # iOS-style icons
  flutter_spinkit: ^5.2.1                    # Loading animations
  vector_graphics: ^1.1.19                   # SVG support with better performance
  vector_graphics_compiler: ^1.1.19          # SVG compiler
  animated_text_kit: ^4.2.3                  # Text animations
  easy_stepper: ^0.8.5+1                     # Step progress indicators
  fl_chart: ^0.69.0                          # Charts and graphs
  shimmer: ^3.0.0                            # Shimmer loading effects
  skeletonizer: ^2.1.0+1                     # Skeleton loading screens
  number_pagination: ^1.1.6                  # Pagination components
  iconsax_flutter: ^1.0.1                    # Iconsax icon pack
  google_fonts: ^6.3.0                       # Custom fonts

  # Development & Debugging
  flutter_screenutil: ^5.9.3                 # Responsive UI adaptation

  # Navigation & State Management
  get: ^4.7.2                                # GetX for state management & navigation
  get_storage: ^2.1.1                        # Local storage for GetX

  # Utilities & Helpers
  async: ^2.13.0                             # Async utilities
  dartz: ^0.10.1                             # Functional programming helpers
  logger: ^2.6.1                             # Logging utility
  fluttertoast: ^9.0.0                      # Toast messages
  url_launcher: ^6.3.2                       # Launch external URLs
  package_info_plus: ^8.3.0                  # App package information

  # Localization & Internationalization
  intl: ^0.20.2                              # Internationalization and localization
  flutter_localization: ^0.3.3
  flutter_quill: ^11.5.0

  # Network & API
  dio: ^5.8.0+1                              # HTTP client for API calls
  cached_network_image: ^3.4.1               # Cached network images
  connectivity_plus: ^6.1.4                  # Network connectivity check
  internet_connection_checker_plus: ^2.7.2   # Internet connection verification

  pinput: ^6.0.0

  # Firebase
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  uuid: ^4.5.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7
  firebase_app_check: ^0.4.1+3
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.2.1

dev_dependencies:
  freezed: ^2.4.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/
  integrations:
    #    vector_graphics: true
    lottie: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/pngs/splash_screen.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - path: assets/svgs/
      transformers:
        - package: vector_graphics_compiler
    - assets/pngs/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: DecoTypeThuluth
      fonts:
        - asset: assets/fonts/DecoType Thuluth Regular.ttf